name: "GitHub Action for Hasura"
author: "Smplrspace"
description: "Wraps the Hasura CLI to enable common commands."
branding:
  icon: "terminal"
  color: "gray-dark"
runs:
  using: "docker"
  image: "Dockerfile"
